project:
  type: website
  output-dir: docs
  
website:
  title: "SamSzo ConfErrance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - arcanes2023.qmd
      - hdrSamSzo.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



