---
title: "Balpe 2025"
author: "Samuel Szoniecky"
bibliography: ref_balpe2025.bib
format:
  wordcount-html:
    toc: true
    fig-align: center
    cap-location: margin
---

# Jean-Pierre Balpe, (méta-)auteur : l’écriture infinie

Colloque international 12-13 juin 2025 - Université Paris 8, Campus Condorcet

## Des générateurs chaotiques aux IA génératives

### Présentation

[Voir en plein écran](balpe2025/slide.html)

```{=html}
<iframe width="800" height="600" src="balpe2025/slide.html" title="Support de présentation"></iframe>
```

### Résumé

Il y a 30 ans presque jour pour jour, j'ai encontré Jean-Pierre Balpe à Paris dans un café de la rue Saint Denis pour lui présenter mon générateur automatique de textes philosophiques conçu avec Hypercard et inspiré par John Cage, Michel Foucault et les théories du chaos. En cet été 1995, mon ambition était de faire une thèse pour expérimenter les usages des ordinateurs dans les sciences humaines, ce que Jean-Pierre avait défini à l'époque comme une recherche sur : "les analyseurs autonomes de données pour la création d'hypertextes adaptatifs".

10 ans plus tard, je retrouve Jean-Pierre à la Maison Populaire de Montreuil pour un atelier de "Création d’un roman génératif nommé Fiction (fictions)" ou nous expérimentons des fictions générées par le flux des webcams et représentées sous la forme de fullerènes. C'est l'occasion pour moi de renouer avec le département Hypermédia et le laboratoire Paragraphe, de commencer une nouvelle carrière à l'université et de collaborer avec Jean-Pierre à la conception des nouvelles versions de ses générateurs automatiques de textes et à l’expérimentations de nouveaux usages...

Aujourd'hui, au moment où l'Université Paris 8 exprime de plus en plus fortement sa volonté d'être une "université des créations", il nous semble important en tant que participant à ces expériences "balpiennes", d'enraciner cette politique institutionnelle dans l'histoire de ceux qui ont habité ce lieu. Jean-Pierre Balpe est sans doute un des acteurs importants de cette manière d’être universitaire qui a fait émerger des enseignants - chercheurs – créateurs. Nous sommes nombreux à nous frayer un chemin dans les dédales de nos institutions et de nos pensées en suivant les traces que Jean-Pierre nous a laissées, nous a appris à voir et entretenir. Comment retracer ces frayages et analyser l’influence de Jean-Pierre sur eux ?

Nous proposons ici une archéologie des savoirs stimulés par nos rapports avec Jean-Pierre Balpe. Notre objectif n’est pas celui d’un catalogage exhaustif des connaissances, nous souhaitons plutôt montrer quelques fragments de cette histoire qui nous semble particulièrement important. Pour ce faire, nous utiliserons la méthode de modélisation des existences informationnelles que nous avons conçu pour quantifier la complexité d'un évenement et analyser les évolutions des pouvoirs de discernement, de raisonnement et d'agir.

### Biographie

Après des recherches en histoire de l’art (1995 DEA sur John Cage) et une formation autodidacte aux développements numériques, Samuel Szoniecky suit une carrière d’ingénieur informatique pour des grands comptes, puis de chef de projet et de créateur d’entreprise. Depuis 2006, il oriente son travail vers la recherche et l’enseignement à l’université Paris 8 dans le laboratoire Paragraphe où en 2013 il devient maître de conférences en sciences de l’information et de la communication. Il explore des méthodes de design des connaissances pour le développement d’une intelligence collective centrée sur la stimulation, l’expression et le partage des intelligences individuelles. [Plus de détails](https://www.samszo.univ-paris8.fr/omk/s/fiches/page/cv "Plus de détails")