---
title: "SOCIN’ 25 proposition Samuel Szoniecky"
author: "Samuel Szoniecky"
bibliography: ref_SOCIN25_propSamSzo.bib
format:
  wordcount-html:
    toc: true
    fig-align: center
    cap-location: margin
---

# SOCIN’ 25 - Repenser l’innovation. Pratiques inclusives et perspectives interdisciplinaires

Congrès annuel de l’Alliance ERUA - SOCIN’25 Du 23 au 26 septembre 2025 Université de Macerata (Italie)

## Cartographie des souvenirs pour une archéologie des créations à Paris 8 : Conception d'un environnement numérique de captation des souvenirs et d'exploration des récits mémoriels

### Résumé

Le centre expérimental de Vincennes est relativement connue et a fait l'objet de publications [@soulié2012; @merlin1979; @merlin1980; @ohayon2022; @grésillon2021], d'une thèse [@dormoy-rajramanan2014], d'un film documentaire [@sluys2018], d'une émission de radio [@mauduit]... Une fois déménagée à Saint-Denis, ce centre devenu l'Université Paris 8 continue son histoire mais celle-ci est bien moins documentée et a fait l'objet d'une moins grande attention. L'objectif de cette recherche est d'explorer cette mémoire de Paris 8 à Saint Denis. Plus particulièrement, nous souhaitons nous focaliser sur un aspect particulier de cette université celui de la création numérique [@eymet2016] qui à travers les disciplines encore non enseignées à l'université dans les années 80 comme l'hypermédia et l'intelligence artificielle, se fraye [@citton2010] un chemin dans les pratiques universitaires jusqu'aujourd'hui où Paris 8 proclame "les créations" comme moteur de son avenir.

Nous concevons ce projet comme une démarche interdisciplinaire qui vise n'ont pas l'exaustivité des témoignages, ni un catalogue d'événements dans une chronologie figée mais la conception d'un environnement éditorial qui s'enrichie récursivement au fur et à mesure des contributions et de l'expression des points de vues.

Nous avons montré dans [@szoniecky2019] comment ce type de démarche éditoriale oscille entre une volonté d'exprimer des faits formellement interopérables pour construire une argumentation logique et celle d'une expression plus intuitives qui stimule une inspiration créative et une expression plus émotionnelle. Dans le projet qui nous occupe ici à savoir la cartographie des souvenirs pour une archéologie des créations à Paris 8, nous devons prendre en compte ces deux modes d'éditorialisation puisque la cartographie est un exercice formel et le souvenir une pratique intuitive. Associé ces deux démarches permet tout à la fois de rendre interopérable les contenus édités mais aussi de laisser une grande liberté à l'expression des témoignages.

Un autre point très important que nous souhaitons mettre au cœur de cette environnement éditorial, concerne la place de la médiation humaine dans le processus éditorial. Nous croyons qu'à l'heure de la prolifération des IA, il est fondamental de ne pas les utiliser pour la production intensive de contenus. Il nous semble que les réflexions autour de la qualité de ce que produit l'IA par exemple en terme de pertinence du propos, de corrections des biais ou de corrélation avec l'expression humaine... sont beaucoup moins importantes que les recherches sur les moyens d'utiliser l'IA pour faire émerger une intelligence collective [@lévy2011], une éthique de la discussion [@habermas2013] et des usages écologiquement responsables[@lefevre2023]. Ce qui importe c'est moins la réponse à des impératifs de productivité inhérents à une évaluation quantitative de la recherche plutôt que la construction collective d'enjeux communs dont la complexité nécessite des capacités d'organisation et de calcul auxquelles les IA peuvent sans doute continuées. Encore faut-il laissé une place importante aux humains pour qu'ils expriment leurs expertises mais aussi leurs questionnements, leurs doutes et leurs peurs. Il nous faut à la fois gagner en efficacité organisationnelle et ne pas perdre la dimension émotionnelle des rapports humains qui est indispensable à une démarche éthique qui prend en compte l'altérité et l'émergence de point de vue différents.

### Biographie

Après des recherches en histoire de l’art (1995 DEA sur John Cage) et une formation autodidacte aux développements numériques, Samuel Szoniecky suit une carrière d’ingénieur informatique pour des grands comptes, puis de chef de projet et de créateur d’entreprise. Depuis 2006, il oriente son travail vers la recherche et l’enseignement à l’université Paris 8 dans le laboratoire Paragraphe où en 2013 il devient maître de conférences en sciences de l’information et de la communication. Il explore des méthodes de design des connaissances pour le développement d’une intelligence collective dans des projets d'Humanités numériques centrés sur la stimulation, l’expression et le partage des intelligences individuelles. [Plus de détails](https://www.samszo.univ-paris8.fr/omk/s/fiches/page/cv "Plus de détails")